[env:adafruit_feather_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit AMG88xx Library
    tanakamasayuki/TensorFlowLite_ESP32
